PelimaailmaAdmin/PelimaailmaAdmin/Controllers/TyontekijasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PelimaailmaAdmin.Models;

namespace PelimaailmaAdmin.Controllers
{
    public class TyontekijasController : Controller
    {
        private pelimaailmaEntities db = new pelimaailmaEntities();

        // GET: Tyontekijas
        public ActionResult Index()
        {
            return View(db.Tyontekija.ToList());
        }

        // GET: Tyontekijas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tyontekija tyontekija = db.Tyontekija.Find(id);
            if (tyontekija == null)
            {
                return HttpNotFound();
            }
            return View(tyontekija);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PelimaailmaAdmin/PelimaailmaAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pelimaailma Oy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pelimaailma", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Etusivu", "Index", "Home")</li>
                    <li>@Html.ActionLink("Pelit", "Index", "Pelit")</li>
                    <li>@Html.ActionLink("Tyontekijat", "Index", "Tyontekijas")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pelimaailma Oy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>